### ISSUE TITLE
Unable to run my_first_score.qasm

### ISSUE THREAD

**Issue by gubiithefish** [Qiskit/ibmqx-user-guides#40]
Step 1: Copy code from [my_first_score.qasm](https://github.com/Qiskit/ibmqx-user-guides/blob/master/qiskit/openqasm/my_first_score.qasm)
Step 2: Insert code into [QASM Editor on IBM Q Experience](https://quantumexperience.ng.bluemix.net/qx/qasm)
Step 3: Following error should apprear 
```c++
Error in line 19: CX gate between q[0], q[1] is not allowed in this topology 
```

**Comment by nonhermitian** [comment]
This is a bug in the `my_first_score.qasm` file.  As the image below shows, you can only perform a `cx` gate with `q[1]` as the control and `q[0]` as the target:

<img width="282" alt="screen shot 2019-02-14 at 1 25 48 pm" src="https://user-images.githubusercontent.com/1249193/52808578-3a045e00-305c-11e9-9b1c-7897adc7b54c.png">

**Comment by gubiithefish** [comment]
That makes sense, as the arrows indicate the allowed CNOT operations. 

Then I suppose the `my_first_score.qasm` was build with the connectivity map from ibmqx2 in mind, which is quite different to the connectivity map from ibmqx4.

Thank you for pointing that out, @nonhermitian.
